markdown: rdiscount
permalink: /:title/
url: http://chenweihan.github.io
name: chenweihan
author: chenweihan
qq: 277546785
email: chenweihan163@gmail.com | csq-3@163.com
duoshuo: chenweihan
beian: 
cnzz: 4884698
weibo: 1657941841
github: chenweihan
pygments: true
safe: true
paginate: 20
about: "于2014.03 迁入chenweihan 的个人博客……"
