markdown: rdiscount
permalink: /:title/
url: http://chenweihan.github.com
name: chenweihan
author: chenweihan
qq: 123018
email: chenweihan163@gmail.com
duoshuo: chenweihan
beian: 
cnzz: 4884698
weibo: 1885061391
github: chenweihan
pygments: true
safe: true
paginate: 20
about: "这里是 chenweihan 的个人博客，创建于 2014 年。开始使用了 网易博客 写笔记，随后使用 网易有道笔记 写笔记，最近迁入github。
